name: Publish Solution

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  package:
    runs-on: ubuntu-latest
    name: Package Solution
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Package Solution
      run: |
        # Create release package
        mkdir -p release
        
        # Copy essential files
        cp -r notebooks release/
        cp -r dashboards release/
        cp -r resources release/
        cp -r images release/
        cp databricks.yml release/
        cp README.md release/
        cp NOTICE.md release/
        cp LICENSE.md release/
        cp SECURITY.md release/
        cp CONTRIBUTING.md release/
        cp requirements.txt release/
        cp env.example release/
        
        # Create archive
        tar -czf prospect-analyzer-${{ github.event.release.tag_name || 'latest' }}.tar.gz release/
    
    - name: Upload Release Asset
      if: github.event.release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./prospect-analyzer-${{ github.event.release.tag_name }}.tar.gz
        asset_name: prospect-analyzer-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip

  publish-docs:
    runs-on: ubuntu-latest
    name: Publish Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install markdown beautifulsoup4
    
    - name: Generate Documentation Site
      run: |
        mkdir -p site
        
        # Convert README to HTML with enhanced styling
        python3 << 'EOF'
        import markdown
        import os
        
        # Read README.md
        with open('README.md', 'r') as f:
            readme_content = markdown.markdown(f.read(), extensions=['fenced_code', 'tables'])
        
        # Get repository info
        repo_name = os.environ.get('GITHUB_REPOSITORY', '').split('/')[-1]
        title = 'Prospect Analyzer - AI-Powered Prospecting Tool'
        
        # Create enhanced HTML
        html = f'''<!DOCTYPE html>
        <html>
        <head>
            <title>{title}</title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
            <style>
                * {{ box-sizing: border-box; }}
                body {{ 
                    font-family: 'DM Sans', sans-serif; 
                    margin: 0; 
                    padding: 0; 
                    background: #FFFFFF; 
                    color: #1B3139; 
                    line-height: 1.6;
                }}
                
                .header {{ 
                    background: #FFFFFF; 
                    padding: 20px 40px; 
                    border-bottom: 2px solid #FF3621; 
                    display: flex; 
                    align-items: center; 
                    gap: 24px; 
                    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                }}
                
                .logo {{ height: 32px; }}
                .title {{ font-size: 24px; font-weight: 700; flex: 1; color: #1B3139; }}
                .github-link {{ 
                    background: #FF3621; 
                    color: white; 
                    padding: 12px 24px; 
                    border-radius: 8px; 
                    text-decoration: none; 
                    font-weight: 600; 
                    font-size: 16px;
                    transition: all 0.2s;
                }}
                .github-link:hover {{ background: #E33417; }}
                
                .container {{ 
                    max-width: 1200px; 
                    margin: 0 auto; 
                    padding: 40px 20px; 
                }}
                
                .content {{ 
                    background: #FFFFFF; 
                    padding: 40px; 
                    border-radius: 12px; 
                    box-shadow: 0 4px 12px rgba(0,0,0,0.1); 
                }}
                
                h1, h2, h3, h4, h5, h6 {{ 
                    color: #1B3139; 
                    font-weight: 600; 
                }}
                h1 {{ font-size: 36px; margin: 0 0 24px 0; }}
                h2 {{ font-size: 28px; margin: 32px 0 16px 0; }}
                h3 {{ font-size: 22px; margin: 24px 0 12px 0; }}
                
                p {{ margin: 0 0 16px 0; }}
                
                code {{ 
                    background: #F5F5F5; 
                    padding: 2px 8px; 
                    border-radius: 4px; 
                    font-family: 'Monaco', 'Consolas', monospace; 
                    font-size: 14px;
                }}
                
                pre {{ 
                    background: #F8F9FA; 
                    padding: 20px; 
                    border-radius: 8px; 
                    overflow-x: auto; 
                    margin: 16px 0; 
                    border: 1px solid #E3E3E3;
                }}
                
                pre code {{ 
                    background: transparent; 
                    padding: 0; 
                }}
                
                img {{ 
                    max-width: 100%; 
                    height: auto; 
                    display: block; 
                    margin: 20px auto; 
                    border-radius: 8px; 
                    box-shadow: 0 4px 12px rgba(0,0,0,0.1); 
                }}
                
                table {{ 
                    width: 100%; 
                    border-collapse: collapse; 
                    margin: 20px 0; 
                }}
                
                th, td {{ 
                    border: 1px solid #E3E3E3; 
                    padding: 12px; 
                    text-align: left; 
                }}
                
                th {{ 
                    background: #F5F5F5; 
                    font-weight: 600; 
                }}
                
                a {{ 
                    color: #FF3621; 
                    text-decoration: none; 
                }}
                a:hover {{ 
                    text-decoration: underline; 
                }}
                
                ul, ol {{ 
                    margin: 0 0 16px 0; 
                    padding-left: 24px; 
                }}
                
                li {{ margin: 8px 0; }}
                
                .badge {{ 
                    display: inline-block; 
                    margin: 4px; 
                }}
                
                blockquote {{ 
                    border-left: 4px solid #FF3621; 
                    padding-left: 16px; 
                    margin: 16px 0; 
                    font-style: italic; 
                    color: #666; 
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <img src="https://databricks-prod-cloudfront.cloud.databricks.com/static/811f68f9f55e3a5330b6e6ae1e54c07fc5ec7224f15be529de3400226e2eca3a/db-nav-logo.svg" 
                     class="logo" alt="Databricks">
                <div class="title">{title}</div>
                <a href="{os.environ.get('GITHUB_SERVER_URL', '')}/{os.environ.get('GITHUB_REPOSITORY', '')}" 
                   class="github-link">View on GitHub</a>
            </div>
            
            <div class="container">
                <div class="content">
                    {readme_content}
                </div>
            </div>
        </body>
        </html>'''
        
        with open('site/index.html', 'w') as f:
            f.write(html)
        
        print("Generated documentation site")
        EOF
    
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'site'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4